language: node_js
script:
  - npm run build
env:
  global:
    - secure: Nlyy8DmuByAYEtTWrHHIf7pS60mPWwGIAw7r41dmzlB+ONN1ePhRWyw/XiRYTsumzjkaw1RdZrYIob6tTRXemhvaEeXl4IEv20zyaIbVqOhWSV54FE8AsIWPIBSIuSiKESGvPeT1RUcB2lV0XHY0eGodn+Ek43OJnQCF/axnEOxIDrXPFeIqkdUQWZ6WCfpy/NIX2fFsSgafYzEdnep9nLXvNiUjUj4M2YuoiqtWbMgdUO05bZ/QXSUw4h1q5JRch3qbHZV4kYTof7rSsToE4dzcPdicd/D98T8frmysMlAxcMUTopRrwYYdzloEwfuoxzLkPUJ6BHKRr55bMo1yna7jk9BdJp2zrnC8alswJJX0fAPD+aIx4OMNeWT9gVzvl/PzWx7LCtMuIMyMyzaJ7CK8Tf68bM3BQHx/cW8QQzH/1iFZ2Hdd3Q/fmBderWKgPjQpZ2spjkfhfLSLHmFVOPCv12QX+/i3+UMldI/31oeSQJD7GtP/Z7Pcmxo6vFR/qK4Ak0WnFu3h8XPxnzzdhC93YwOqT07VZIH2lat4CGzfKw+fdFY0BdSF2q6+aY4hYwSOT8aMnc3BjuBOPVI9Uga1VSwDJZrXipAsm163uhZACSCwNc/5csH5+WXnNidgKaLUND5IZTVqxduFtKS+nTDAfwGpDJjOD/AgErgR9vc=
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
